---

app_name:               application_default

fpm_pool_path:          /etc/php5/fpm/pool.d

listen:                 /var/run/{{ app_name }}.sock
listen_owner:           www-data
listen_group:           www-data
listen_mode:            0666

fpm_user:               www-data
fpm_group:              www-data

fpm_method:             dynamic
max_children:           500
start_servers:          5
min_spare_servers:      1
max_spare_servers:      50
max_requests:           500
status_path:            /fpm_status_{{ app_name }}

listen_backlog:         4096

packages:
    - php5-fpm

