FROM debian:9

RUN apt-get update
RUN apt-get -y install python-pip python-dev curl
RUN pip install --upgrade pip
RUN pip install --upgrade PyOpenSSL cryptography ansible
RUN curl -fsSL https://goss.rocks/install | sh

WORKDIR /ansible
