---

- name: Install fpm packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
     "{{ packages }}"
  tags: fpm_pkgs

- name: Configure fpm general settings
  template: src=fpm.conf.j2 dest=/etc/php5/fpm/php-fpm.conf owner=root group=root mode=0644
  tags: fpm_cfg
  notify:
    - reload fpm

- name: Configure pool for {{ app_name }}
  template: src=pool.j2 dest={{ fpm_pool_path }}/{{ app_name }}.conf owner=root group=root mode=0644
  tags: fpm_pool
  notify:
    - reload fpm

- name: Ensure fpm is running
  service: name=php5-fpm state=running enabled=yes
  tags: fpm


