---

os_flavor: "{{ ansible_os_family | lower }}"

packages:
  debian:
    - vim
    - dnsutils
    - mtr-tiny
    - whois
    - net-tools
    - htop
    - sudo
    - telnet
    - python-pip
    - python-boto
    - mlocate
    - ntp
    - tcpdump
    - nmap
    - git
    - less
    - curl
    - tzdata
    - nginx
  redhat:
    - vim-minimal
    - bind-utils
    - mtr
    - jwhois
    - net-tools
    - htop
    - sudo
    - telnet
    - python-pip
    - python-boto
    - mlocate
    - ntp
    - tcpdump
    - nmap
    - git
    - less
    - curl
    - tzdata
    - nginx
