version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: "[ Debian ]:  Build ansible image"
          command: docker-compose build debian
      - run:
          name: "[ CentOS ]: Build ansible image"
          command: docker-compose build centos
      - run:
          name: "[ Debian ]: Run ansible tests"
          command: docker-compose run debian
      - run:
          name: "[ CentOS ]:  Run ansible tests"
          command: docker-compose run centos
