version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: Debian  Build ansible image
          command: docker-compose build debian
      - run:
          name: validate build
          command: docker-compose run debian ls -la / /ansible /root
      - run:
          name: Debian  Run ansible tests
          command: docker-compose run debian
