---
  package:
    {{ if eq .Vars.ansible_facts.ansible_os_family "RedHat" }}
    vim-minimal:
      installed: true
    bind-utils:
      installed: true
    mtr:
      installed: true
    jwhois:
      installed: true
    {{ end }}
    {{ if eq .Vars.ansible_facts.ansible_os_family "Debian" }}
    vim:
      installed: true
    dnsutils:
      installed: true
    mtr-tiny:
      installed: true
    whois:
      installed: true
    {{ end }}
    net-tools:
      installed: true
    htop:
      installed: true
    sudo:
      installed: true
    telnet:
      installed: true
    python-pip:
      installed: true
    python-boto:
      installed: true
    mlocate:
      installed: true
    ntp:
      installed: true
    tcpdump:
      installed: true
    nmap:
      installed: true
    git:
      installed: true
    less:
      installed: true
    curl:
      installed: true
    tzdata:
      installed: true
