---

- name: Install default packages
  package:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     "{{ packages[os_flavor] }}"
  tags: pkgs

- name: Add sudo group
  group:
    name: sudo
    state: present
  tags:
    - users
    - common

- name: Update sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
  tags:
    - users
    - common

- name: Add Users
  user:
    name: "{{ item.key }}"
    shell: /bin/bash
    comment: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    groups: "{{ item.value.groups }}"
  with_dict:
    "{{ users | default({}) }}"
  tags:
    - users
    - common

- name: Authorized common users keys
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value.pub_key }}"
  when: item.value.state != "absent"
  with_dict:
    "{{ users | default({}) }}"
  tags:
    - users
    - common


